sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
      - udf_coverage
linkReplacements:
build:
  # UDFs in Exasol 7.1 require Ubuntu 20.04
  runnerOs: ubuntu-20.04
  freeDiskSpace: true
  exasolDbVersions:
    - "8.31.0" # Tests fail with 8.32.0, see https://github.com/exasol/virtual-schema-common-document/issues/193
    - "7.1.30"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Configure Google credentials
            id: configure-google-credentials
            run: echo "$GC_KEY" > google-key.json
            env:
              GC_KEY: ${{ secrets.GC_KEY }}
